//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace windowsproje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanıcılar
    {
        public int Id { get; set; }
        [Required(ErrorMessage = " Kullanıcı adı gereklidir", AllowEmptyStrings = false)]
        public string Username { get; set; }

        [Required(ErrorMessage = " Şifre gereklidir", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Mail { get; set; }
        public int Yetki { get; set; }
        public string FullName { get; set; }
    }
}
