//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace windowsproje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kuponlar
    {

        public int KuponID { get; set; }

        [Display(Name = "Kupon Adı")]
        public string KuponAd { get; set; }

        [Display(Name = "Kupon Detayı")]
        public string KuponDetay { get; set; }

        [Display(Name = "Kupon Resmi")]
        public byte[] KuponResim { get; set; }

        [Display(Name = "Kupon İli")]
        public string Kuponİl { get; set; }

        [Display(Name = "Kupon Adresi")]
        public string KuponAdres { get; set; }

        [Display(Name = "Kupon Bitiş Tarihi")]
        public string KuponTarih { get; set; }
        public System.DateTime KayıtTarih { get; set; }

        [Display(Name = "Kupon Kategorisi")]
        public int KategoriID { get; set; }

        [Display(Name = "Kupon Ücreti")]
        public int KuponÜcret { get; set; }

        [Display(Name = "Kupon Stoğu")]
        public int Stok { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
